version: 2.1
jobs:
 build:
  docker:
   - image: python:3.10.6
  auth:
   username: materacmaxence@gmail.com
   password: Maxcle43! # context / project UI env-var reference
  steps:
# etape 1 : obtenir le referentiel github
   - checkout
   - run: python --version
# etape 2 : creer un environnement virtuel et creer les dependances
   - run:
     name: install dependencies
     command: python3 -m venv venv && . venv/bin/activate && pip install -r requirements.txt
# etape 3 : executer linter et tests
   - run:
     name: run tests
     command: . venv/bin/activate && flake8 --exclude=venv* --statistics && pytest -v --cov=calculator
